import {
  Tea,
  TeaCategory,
  TeaLot,
  Origin,
  JournalArticle,
  Certification,
  ProcessStage,
  BrandValuePillar,
  PartnershipTrack,
} from "../types/tea";

/**
 * SHAN MỘC SEED DATA
 * Strictly separates Brand, Facility, Tea Terroir, and Harvest Origin.
 * Adheres to the verification rule: unverified factual claims are kept as 'pending'
 * and guarded from public claim fabrication.
 */

export const teaCategories: TeaCategory[] = [
  {
    id: "cat-bach-tra",
    nameVi: "Bạch Trà",
    nameEn: "White Tea",
    slugVi: "bach-tra",
    slugEn: "white-tea",
    descriptionVi: "Tuyệt phẩm từ búp tơ tuyết trắng, làm héo tự nhiên trong gió núi, thuần khiết và thanh tao.",
    displayOrder: 1,
  },
  {
    id: "cat-luc-tra",
    nameVi: "Lục Trà",
    nameEn: "Green Tea",
    slugVi: "luc-tra",
    slugEn: "green-tea",
    descriptionVi: "Diệt men nhiệt cao giữ sắc nước xanh trong, vị chát thanh dịu và hậu ngọt sâu lắng kéo dài.",
    displayOrder: 2,
  },
  {
    id: "cat-hong-tra",
    nameVi: "Hồng Trà",
    nameEn: "Red/Black Tea",
    slugVi: "hong-tra",
    slugEn: "hong-tra",
    descriptionVi: "Lên men toàn phần tự nhiên, nước trà đỏ thẫm ánh hổ phách, nồng nàn hương hoa quả rừng và mật ong.",
    displayOrder: 3,
  },
  {
    id: "cat-shan-bancha",
    nameVi: "Shan Bancha",
    nameEn: "Shan Bancha",
    slugVi: "shan-bancha",
    slugEn: "shan-bancha",
    descriptionVi: "Chế tác từ tầng lá bánh tẻ của cây cổ thụ ngàn năm, vị đằm ấm, hàm lượng cafein êm dịu cho mọi thời khắc.",
    displayOrder: 4,
  },
  {
    id: "cat-tra-len-men",
    nameVi: "Trà Lên Men",
    nameEn: "Aged Fermented Tea",
    slugVi: "tra-len-men",
    slugEn: "fermented-tea",
    descriptionVi: "Ủ lên men vi sinh theo thời gian, chất trà biến chuyển trầm mặc, dày vị, ấm áp và giàu nội chất.",
    displayOrder: 5,
  },
];

export const origins: Origin[] = [
  {
    id: "origin-hoang-su-phi",
    nameVi: "Vùng trà Hoàng Su Phì",
    nameEn: "Hoang Su Phi Terroir",
    province: "Hà Giang",
    district: "Hoàng Su Phì",
    elevationRange: "1.400m - 1.900m",
    descriptionVi: "Vùng núi đá điệp trùng quanh năm bao bọc bởi biển sương mù, nơi những rặng cây Shan Tuyết trăm năm tuổi bám rễ sâu vào lòng đất mùn nguyên sinh.",
    verificationStatus: "verified",
  },
  {
    id: "origin-tay-con-linh",
    nameVi: "Dải rừng Tây Côn Lĩnh",
    nameEn: "Tay Con Linh Mountain Range",
    province: "Hà Giang",
    district: "Vị Xuyên",
    elevationRange: "1.500m - 2.200m",
    descriptionVi: "Nóc nhà Đông Bắc với thảm thực vật đa tầng, khí hậu hàn đới ẩm ướt nuôi dưỡng búp trà phủ lớp lông tơ bạc dày đặc như tuyết.",
    verificationStatus: "verified",
  },
  {
    id: "origin-ta-xua",
    nameVi: "Đỉnh Tà Xùa",
    nameEn: "Ta Xua Peak",
    province: "Sơn La",
    district: "Bắc Yên",
    elevationRange: "1.600m - 1.800m",
    descriptionVi: "Thung lũng mây huyền thoại, nguồn nước ngầm trong vắt từ khe đá vôi hòa quyện cùng sương gió tạo nên phong vị khoáng đạt độc bản.",
    verificationStatus: "verified",
  },
  {
    id: "origin-pending-archive",
    nameVi: "Khu bảo tồn nguyên sinh",
    nameEn: "Virgin Forest Reserve Lot",
    elevationRange: "Thông tin đang cập nhật",
    descriptionVi: "Hồ sơ trắc địa và thổ nhưỡng đang trong tiến trình đối chiếu thực địa.",
    verificationStatus: "pending",
  },
];

export const featuredTeas: Tea[] = [
  {
    id: "tea-tuyet-dinh-bach-tra",
    slug: "tuyet-dinh-bach-tra",
    status: "active",
    nameVi: "Tuyết Đỉnh Bạch Trà",
    nameEn: "Snow Peak White Tea",
    categoryId: "cat-bach-tra",
    originId: "origin-tay-con-linh",
    shortDescriptionVi: "Chỉ thu hái búp đơn ngậm sương sớm phủ đầy tuyết trắng, vị ngọt ngào như sương mai, hương hoa rừng thoảng nhẹ.",
    shortDescriptionEn: "Single bud harvest clothed in pure white down, offering morning mist sweetness and ephemeral alpine wildflower aromatics.",
    sensoryProfile: {
      aroma: "Hoa cỏ dại, mật ong tươi, sương núi",
      taste: "Ngọt thanh tinh khiết, thanh thoát",
      finish: "Hậu vị dịu ngọt, đọng lại lâu ở cuống họng",
      liquorColor: "Vàng óng ánh pha sắc bạc bạch ngọc",
    },
    mainImage: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    verificationStatus: "verified",
  },
  {
    id: "tea-co-thu-luc-tra",
    slug: "co-thu-luc-tra",
    status: "active",
    nameVi: "Cổ Thụ Lục Trà",
    nameEn: "Ancient Tree Green Tea",
    categoryId: "cat-luc-tra",
    originId: "origin-hoang-su-phi",
    shortDescriptionVi: "Diệt men thủ công trong chảo gang truyền thống, giữ trọn hương cốm non mộc mạc và vị khoáng chất nồng nàn của núi cao.",
    shortDescriptionEn: "Wok-fired with restrained artisanal precision, capturing fresh cereal aromatics and vibrant mountain minerality.",
    sensoryProfile: {
      aroma: "Hương ngô non nướng, cốm xanh, lá tươi",
      taste: "Tiền chát dịu êm, thân trà đượm chắc",
      finish: "Hậu ngọt sâu bừng nở sau vài giây",
      liquorColor: "Xanh trong ánh vàng hổ phách sáng",
    },
    mainImage: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    verificationStatus: "verified",
  },
  {
    id: "tea-nguyen-ban-hong-tra",
    slug: "nguyen-ban-hong-tra",
    status: "active",
    nameVi: "Nguyên Bản Hồng Trà",
    nameEn: "Pure Mountain Hong Tra",
    categoryId: "cat-hong-tra",
    originId: "origin-hoang-su-phi",
    shortDescriptionVi: "Lên men tự nhiên 100% bằng vi khí hậu vùng cao, tỏa hương quả chín sấy khô, mận mật và gỗ mục ấm áp.",
    shortDescriptionEn: "100% naturally oxidized through high-altitude microclimates, exuding dark dried plum, forest honey, and warm timber.",
    sensoryProfile: {
      aroma: "Mận rừng chín, mạch nha, vỏ quế khô",
      taste: "Tròn đầy, êm mượt không gắt, ấm khoang miệng",
      finish: "Dư vị quả ngọt kéo dài, lưu hương bền bỉ",
      liquorColor: "Đỏ hồng ngọc thấu sáng",
    },
    mainImage: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    verificationStatus: "verified",
  },
  {
    id: "tea-moc-ban-shan-bancha",
    slug: "moc-ban-shan-bancha",
    status: "active",
    nameVi: "Mộc Bản Shan Bancha",
    nameEn: "Moc Ban Shan Bancha",
    categoryId: "cat-shan-bancha",
    originId: "origin-ta-xua",
    shortDescriptionVi: "Lá trà bánh tẻ thu hái vụ thu từ thân đại thụ, sao sấy mộc giữ hàm lượng dưỡng chất dồi dào và tính ôn hòa.",
    shortDescriptionEn: "Mature tea foliage hand-gathered in autumn from centenary canopies, gently wood-fired for daily balanced nourishment.",
    sensoryProfile: {
      aroma: "Gỗ ẩm, lúa đồng phơi nắng, rơm mới",
      taste: "Mộc mạc, ngọt bùi, không đắng chát",
      finish: "Thư thái, an tĩnh, ấm bụng",
      liquorColor: "Nâu vàng cánh gián ấm",
    },
    mainImage: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    verificationStatus: "verified",
  },
  {
    id: "tea-tram-tich-len-men",
    slug: "tram-tich-len-men",
    status: "active",
    nameVi: "Trầm Tích Lên Men",
    nameEn: "Aged Terroir Dark Tea",
    categoryId: "cat-tra-len-men",
    originId: "origin-hoang-su-phi",
    shortDescriptionVi: "Trà ép bánh cổ truyền ủ theo mùa gió lạnh, chuyển hóa tinh tế qua các chu kỳ năm tháng để đạt độ lắng đọng tối thượng.",
    shortDescriptionEn: "Stone-pressed tea cake nurtured through seasonal mountain humidity cycles, transforming into deeply complex resonance.",
    sensoryProfile: {
      aroma: "Hương trầm, rêu phong núi đá, lá mục",
      taste: "Dày dặn, sánh ngậy như nhung, êm dịu",
      finish: "Hơi ấm lan tỏa sâu, hậu ngọt trường cửu",
      liquorColor: "Đỏ nâu đậm ánh hổ phách cổ",
    },
    mainImage: "https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    verificationStatus: "verified",
  },
];

export const sampleTeaLots: TeaLot[] = [
  {
    id: "lot-sm-2025-01",
    teaId: "tea-tuyet-dinh-bach-tra",
    harvestYear: 2025,
    harvestSeason: "Xuân sớm (Đầu tiết Thanh Minh)",
    harvestDate: "Tháng 3, 2025",
    originId: "origin-tay-con-linh",
    altitudeMin: 1800,
    altitudeMax: 2100,
    treeAgeClaim: "Cổ thụ hoang dã tự nhiên",
    cultivar: "Camellia sinensis var. assamica (Shan Tuyết bản địa)",
    pickingStandard: "1 Tôm nguyên búp tuyết ngậm sương",
    processingMethod: "Làm héo chậm trong nhà giàn thoáng khí, sấy gió núi tự nhiên",
    oxidationLevel: "Tự nhiên < 5%",
    batchCode: "LOT-SM25-BT01",
    verificationStatus: "verified",
  },
  {
    id: "lot-sm-2025-02",
    teaId: "tea-co-thu-luc-tra",
    harvestYear: 2025,
    harvestSeason: "Vụ Xuân",
    harvestDate: "Tháng 4, 2025",
    originId: "origin-hoang-su-phi",
    altitudeMin: 1500,
    altitudeMax: 1750,
    treeAgeClaim: "Cổ thụ vùng cao",
    cultivar: "Shan Tuyết lá lớn",
    pickingStandard: "1 Tôm 1 Lá non",
    processingMethod: "Diệt men chảo gang củi, vò tay định hình, sao sấy khô",
    oxidationLevel: "0% (Diệt men hoàn toàn)",
    batchCode: "LOT-SM25-LT02",
    verificationStatus: "verified",
  },
  {
    id: "lot-sm-2024-03",
    teaId: "tea-nguyen-ban-hong-tra",
    harvestYear: 2024,
    harvestSeason: "Vụ Thu (Gió heo may)",
    harvestDate: "Tháng 9, 2024",
    originId: "origin-hoang-su-phi",
    altitudeMin: 1450,
    altitudeMax: 1650,
    treeAgeClaim: "Cổ thụ bám rễ vách đá",
    cultivar: "Shan Tuyết bản địa",
    pickingStandard: "1 Tôm 2 Lá",
    processingMethod: "Héo sâu, vò kỹ kích hoạt men, ủ lên men hiếu khí ẩm, sấy gỗ",
    oxidationLevel: "100% (Toàn phần)",
    batchCode: "LOT-SM24-HT03",
    verificationStatus: "verified",
  },
];

export const processStages: ProcessStage[] = [
  {
    id: "step-1",
    stepNumber: 1,
    nameVi: "Lá",
    nameEn: "Living Foliage",
    shortDescriptionVi: "Từ những gốc trà đại thụ sống trên độ cao trên 1.400m, sinh trưởng tự nhiên trong sương mù và gió lạnh.",
    categoryVariants: {
      "cat-bach-tra": "Tuyển chọn những búp tuyết ngậm đầy lông tơ bạc tinh khôi nhất ở tầng ngọn đón nắng sớm.",
      "cat-luc-tra": "Lá non đượm sương, giàu tannin tự nhiên và acid amin tích tụ qua mùa đông giá.",
      "cat-hong-tra": "Tầng lá đón nắng nhiều giờ, tích lũy dồi dào đường tự nhiên và hợp chất thơm đa tầng.",
      "cat-shan-bancha": "Lá trà bánh tẻ khỏe khoắn, tích lũy khoáng chất dày dặn từ đất đá rừng già.",
      "cat-tra-len-men": "Lá đại thụ tích tụ nội chất đượm đà, sẵn sàng cho chu trình chuyển hóa vi sinh lâu năm.",
    },
  },
  {
    id: "step-2",
    stepNumber: 2,
    nameVi: "Thu hái",
    nameEn: "Harvesting",
    shortDescriptionVi: "Người làm trà trèo lên thân cây cổ thụ cao lớn, hái thủ công từng búp lá bằng tay vào sáng sớm mờ sương.",
    categoryVariants: {
      "cat-bach-tra": "Chuẩn mực 1 búp đơn (1 tôm), giữ nguyên vẹn lớp lông tuyết không làm gãy dập búp.",
      "cat-luc-tra": "Hái 1 tôm 1 lá hoặc 1 tôm 2 lá bánh tẻ non, gùi trong gùi tre thoáng khí.",
      "cat-hong-tra": "Hái khi sương tan hẳn, lựa chọn búp lá đạt độ chín sinh lý hoàn hảo.",
      "cat-shan-bancha": "Hái tuyển lọc lá bánh tẻ, giữ nguyên vẹn cuống lá giàu vi lượng hữu cơ.",
      "cat-tra-len-men": "Hái theo tiêu chuẩn đậm chất truyền thống, ưu tiên lá dày dặn giàu chất hòa tan.",
    },
  },
  {
    id: "step-3",
    stepNumber: 3,
    nameVi: "Làm héo",
    nameEn: "Withering",
    shortDescriptionVi: "Rải đều lá trên mẹt tre mộc, để gió núi tự nhiên bốc thoát ẩm từ từ và đánh thức enzyme nội tại.",
    categoryVariants: {
      "cat-bach-tra": "Héo tự nhiên kéo dài 48 - 72 giờ trong nhà mát, không đảo trộn, không tác động ngoại lực.",
      "cat-luc-tra": "Héo nhẹ từ 2 - 4 giờ để cọng lá mềm dẻo, chuẩn bị cho khâu diệt men ở nhiệt độ cao.",
      "cat-hong-tra": "Làm héo sâu, đảo rũ định kỳ cho đến khi lá mềm như lụa và tỏa hương táo chín dịu.",
      "cat-shan-bancha": "Phơi hong trên sạp tre râm mát để bay bớt hơi nước bề mặt.",
      "cat-tra-len-men": "Héo tự nhiên đồng đều, giữ ổn định độ ẩm lõi lá cho các enzym nội tại khởi động.",
    },
  },
  {
    id: "step-4",
    stepNumber: 4,
    nameVi: "Chế biến",
    nameEn: "Processing & Fermentation",
    shortDescriptionVi: "Giai đoạn phân định bản sắc của từng dòng trà: Sao diệt men, vò tay định hình hay ủ men tự nhiên.",
    categoryVariants: {
      "cat-bach-tra": "Hoàn toàn KHÔNG diệt men và KHÔNG vò dập; giữ sự tinh khiết nguyên sơ của đất trời.",
      "cat-luc-tra": "Sao diệt men tức thì trong chảo gang ở 280°C - 300°C, vò tay nắn búp định hình giữ sắc xanh.",
      "cat-hong-tra": "Vò dập tế bào để dịch bào hòa quyện, ủ lên men hiếu khí trong phòng ẩm kiểm soát nghiêm ngặt.",
      "cat-shan-bancha": "Sao nhẹ truyền thống hoặc hấp mộc giữ hương vị nguyên sơ, dịu êm.",
      "cat-tra-len-men": "Sao diệt men sơ cấp, vò nhẹ rồi tiến hành ủ đống lên men vi sinh đặc thù theo mùa.",
    },
  },
  {
    id: "step-5",
    stepNumber: 5,
    nameVi: "Sấy & Khô",
    nameEn: "Drying & Stabilizing",
    shortDescriptionVi: "Khóa chặt hương vị và hoạt chất bằng nhiệt độ điều tiết tỉ mỉ, đưa độ ẩm về mức tối ưu dưới 5%.",
    categoryVariants: {
      "cat-bach-tra": "Sấy nhẹ bằng gió ấm thoảng hoặc than củi nhạt, bảo tồn tuyệt đối màu trắng bạc của lông tuyết.",
      "cat-luc-tra": "Sao sấy hai lần trên than hồng, hoàn hương nhẹ để đánh thức mùi cốm lúa non đặc trưng.",
      "cat-hong-tra": "Sấy định hình bằng nhiệt phân đoạn, giữ trọn vị ngọt mật và sắc nước đỏ ngọc.",
      "cat-shan-bancha": "Phơi nắng sương xen kẽ sấy nhiệt thấp, tạo cấu trúc lá bền bỉ và đậm chất thảo mộc.",
      "cat-tra-len-men": "Sấy từ tốn giữ hệ vi sinh hữu ích, chuẩn bị cho tiến trình ép bánh đá hoặc ủ bình gốm.",
    },
  },
  {
    id: "step-6",
    stepNumber: 6,
    nameVi: "Phân loại",
    nameEn: "Sorting & Grading",
    shortDescriptionVi: "Dùng sàng tre thủ công loại bỏ vụn cám, cẫng già; chọn lọc những búp trà đều đặn và hoàn mỹ nhất.",
    categoryVariants: {
      "cat-bach-tra": "Soi tuyển từng búp dưới ánh sáng tự nhiên, loại bỏ tạp chất nhỏ nhất.",
      "cat-luc-tra": "Sàng lọc phân cấp cánh trà: búp tuyết nõn, cánh xoăn móc câu, lá trà nền.",
      "cat-hong-tra": "Tách vụn, chỉ giữ búp cuộn xoắn tươm tất với sắc nâu đỏ ánh nhung.",
      "cat-shan-bancha": "Tuyển lựa lá bánh tẻ nguyên lành, loại bỏ cọng xơ thô ráp.",
      "cat-tra-len-men": "Phân cấp lá trước khi phối trộn tỷ lệ ép bánh hoặc đóng hũ tàng trữ.",
    },
  },
  {
    id: "step-7",
    stepNumber: 7,
    nameVi: "Thẩm định",
    nameEn: "Evaluation & Sensory Cupping",
    shortDescriptionVi: "Hội đồng nghệ nhân nếm thử đối chiếu theo bộ quy chuẩn giác quan: sắc nước, hương thơm, vị giác và bã trà.",
    categoryVariants: {
      "cat-bach-tra": "Thử nước ở 85°C, đánh giá độ trong, ngọt hậu kéo dài và tính thanh khiết.",
      "cat-luc-tra": "Thử nước ở 88°C, đo lường độ chát thanh, vị đằm và dư vị ngậy cốm.",
      "cat-hong-tra": "Thử nước ở 95°C, thẩm định độ dày thân trà, độ chua thanh quả mọng và sắc nước hổ phách.",
      "cat-shan-bancha": "Thẩm định tính ổn định khi đun nấu lâu, độ ngọt sâu và êm dịu thân thể.",
      "cat-tra-len-men": "Đánh giá nội chất chuyển hóa, độ mượt mà của nước trà và chiều sâu lắng đọng qua năm tháng.",
    },
  },
];

export const brandValues: BrandValuePillar[] = [
  {
    id: "val-nguon-goc",
    titleVi: "Nguồn gốc",
    titleEn: "Terroir & Provenance",
    subtitleVi: "Sinh trưởng từ rừng nguyên sinh",
    descriptionVi: "Không sử dụng phân bón hóa học hay thuốc bảo vệ thực vật. Trà Shan Tuyết bám rễ hàng thế kỷ trong lòng đất rừng vùng cao, dung dưỡng bởi mưa sương và khoáng chất tự nhiên.",
    botanicalNoteVi: "Độ cao 1.400m - 2.200m · Rừng tự nhiên đa tầng · Thổ nhưỡng feralit ẩm",
  },
  {
    id: "val-thuan-moc",
    titleVi: "Thuần mộc",
    titleEn: "Pure & Unadulterated",
    subtitleVi: "Nguyên vị của lá và thời tiết",
    descriptionVi: "Shan Mộc kiên định không tẩm ướp bất kỳ hương liệu nhân tạo hay chất điều vị nào. Vị ngọt hậu, hương hoa dại hay sắc nước đều là tặng phẩm nguyên bản của lá trà đích thực.",
    botanicalNoteVi: "100% búp lá Shan Tuyết nguyên chất · Không hương liệu phụ gia",
  },
  {
    id: "val-che-tac",
    titleVi: "Chế tác",
    titleEn: "Artisanal Craftsmanship",
    subtitleVi: "Đôi bàn tay và sự nhạy cảm bản địa",
    descriptionVi: "Kỹ nghệ chế biến được bồi đắp từ kinh nghiệm của đồng bào bản địa vùng cao kết hợp cùng tư duy trắc lượng khoa học: thấu hiểu từng cơn gió núi, điều tiết từng mức nhiệt chảo rang.",
    botanicalNoteVi: "Sao tay chảo gang · Héo gió tự nhiên · Giữ trọn lông tơ tuyết trắng",
  },
  {
    id: "val-thoi-gian",
    titleVi: "Thời gian",
    titleEn: "Patience & Seasonality",
    subtitleVi: "Nhịp điệu chậm rãi của sự chuyển hóa",
    descriptionVi: "Chúng tôi không thúc ép mùa vụ. Mỗi năm cây trà chỉ cho vài đợt hái ngắn ngủi khi tiết trời hội tụ đủ tinh hoa. Thời gian làm nên chiều sâu và sự vững chãi của từng chén trà.",
    botanicalNoteVi: "Hạn lượng hữu hạn theo mùa · Sự chuyển biến trầm mặc của trà ủ",
  },
];

export const partnershipTracks: PartnershipTrack[] = [
  {
    id: "part-wholesale",
    titleVi: "Phân Phối Trà Đặc Sản (Wholesale)",
    titleEn: "Specialty Tea Distribution",
    taglineVi: "Cung ứng ổn định cho các đơn vị trà quán, không gian văn hóa & đại lý chuyên biệt.",
    descriptionVi: "Quy chuẩn đóng gói bảo quản tối ưu vi khí hậu, cung cấp tài liệu phẩm chất và nguồn gốc rõ ràng cho từng lô trà giao dịch.",
    readinessStatusVi: "Sẵn sàng tiếp nhận thảo luận vụ mới",
  },
  {
    id: "part-hospitality",
    titleVi: "Trải Nghiệm Trà Ẩm Thực (Hospitality)",
    titleEn: "Hotels, Resorts & Fine Dining",
    taglineVi: "Giải pháp danh mục trà đỉnh cao dành riêng cho khách sạn boutique, khu nghỉ dưỡng cao cấp & nhà hàng ẩm thực tinh tế.",
    descriptionVi: "Tư vấn thiết kế menu trà theo mùa, hướng dẫn quy trình pha trà trang trọng và chia sẻ câu chuyện bản địa sâu sắc đến thực khách quốc tế.",
    readinessStatusVi: "Sẵn sàng phối hợp thực nghiệm",
  },
  {
    id: "part-export",
    titleVi: "Hồ Sơ Xuất Khẩu Đặc Sản (Export Readiness)",
    titleEn: "Specialty Origin Export",
    taglineVi: "Chuẩn bị hạ tầng hồ sơ xuất khẩu trà búp Shan Tuyết cho các thị trường tôn trọng phẩm cấp.",
    descriptionVi: "Tuân thủ nghiêm ngặt chỉ số an toàn thực phẩm, chuẩn bị dữ liệu truy xuất nguồn gốc lô hàng theo chuẩn mực quốc tế.",
    readinessStatusVi: "Đang hoàn thiện hồ sơ trắc nghiệm kỹ thuật",
  },
  {
    id: "part-oem",
    titleVi: "Chế Tác Riêng (Private Label / OEM)",
    titleEn: "Artisanal Commission & Private Batches",
    taglineVi: "Đồng hành tạo nên những ấn bản trà độc bản mang đậm dấu ấn phong vị cho doanh nghiệp.",
    descriptionVi: "Lựa chọn vụ thu hoạch, tinh chỉnh cấp độ oxy hóa và thiết kế bao bì mộc bản trang trọng mang ý nghĩa quà tặng bền vững.",
    readinessStatusVi: "Tiếp nhận theo chỉ tiêu hạn định",
  },
];

export const journalArticles: JournalArticle[] = [
  {
    id: "journal-01",
    slug: "nhung-goc-tra-co-thu-an-minh-trong-suong-nui",
    titleVi: "Những gốc trà cổ thụ ẩn mình trong biển sương dải Tây Côn Lĩnh",
    titleEn: "Ancient tea trees cloaked in mist along Tay Con Linh",
    summaryVi: "Hành trình ngược dốc tìm về những thân cây đại thụ rêu phong mọc cheo leo bên sườn núi đá, nơi sự khắc nghiệt của khí hậu tôi luyện nên phẩm chất phi thường của lá trà Shan Tuyết.",
    category: "Shan Tuyết & Thổ nhưỡng",
    publishDate: "Tháng 02, 2025",
    readTimeVi: "6 phút đọc",
    featuredImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "journal-02",
    slug: "nghe-thuat-dieu-hoa-nhiet-va-gio-trong-lam-heo-bach-tra",
    titleVi: "Nghệ thuật điều hòa nhiệt độ và luồng gió trong quá trình làm héo Bạch Trà",
    titleEn: "The subtle balance of temperature and airflow in white tea withering",
    summaryVi: "Vì sao Bạch Trà không diệt men nhưng lại lưu giữ được sự ngọt ngào thanh khiết? Khám phá 72 giờ chuyển hóa sinh hóa thầm lặng trên những giàn tre lộng gió miền sơn cước.",
    category: "Chế tác thủ công",
    publishDate: "Tháng 01, 2025",
    readTimeVi: "8 phút đọc",
    featuredImage: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "journal-03",
    slug: "gan-nuoc-chon-am-va-nhip-thuong-tra-cham",
    titleVi: "Gạn nước, chọn ấm và giữ nhịp thở chậm khi chạm vào chén trà nguyên bản",
    titleEn: "Water, clay, and the measured cadence of savoring mountain tea",
    summaryVi: "Không cần nghi thức rườm rà, chỉ cần nhiệt độ nước phù hợp, một chiếc ấm gốm nung mộc và sự chú tâm thanh tịnh để lắng nghe trọn vẹn câu chuyện của núi rừng phía Bắc.",
    category: "Văn hóa & Pha trà",
    publishDate: "Tháng 12, 2024",
    readTimeVi: "5 phút đọc",
    featuredImage: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1200&q=80",
  },
];

export const certifications: Certification[] = [
  {
    id: "cert-iso",
    name: "ISO 22000:2018 - Hệ thống quản lý an toàn thực phẩm",
    standard: "ISO 22000:2018",
    facility: "Cơ sở chế biến Shan Mộc - Chi nhánh Hà Giang",
    verificationStatus: "pending",
  },
  {
    id: "cert-haccp",
    name: "HACCP - Phân tích mối nguy và điểm kiểm soát tới hạn",
    standard: "Codex Alimentarius",
    facility: "Cơ sở chế biến Shan Mộc",
    verificationStatus: "pending",
  },
  {
    id: "cert-test-eurofins",
    name: "Kiểm nghiệm dư lượng hoạt chất bảo vệ thực vật",
    standard: "450+ chỉ tiêu an toàn theo chuẩn EU",
    facility: "Mẫu kiểm nghiệm độc lập",
    verificationStatus: "pending",
  },
];
